[package]
name = "ms-symfetch"
version = "0.1.0"
edition = "2021"
authors = ["ezekiel <ezekiel@arcadian.garden>"]
license = "Apache-2.0 OR MIT"

[dependencies]
cargo-deny = "0.14.3"
clap = { version = "4.4.7", features = ["derive"] }
ureq = "2.8.0"
